import random
import string
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserAdditionalInformation(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default="image.jpg")
    phone = models.CharField(max_length=15, null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} Additional Information"


class Vendor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    vendor_whatsapp_url = models.URLField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Vendor {self.user.first_name} {self.user.last_name}"


class CouponCode(models.Model):
    coupon_code = models.CharField(max_length=255, null=True, blank=True, unique=True, editable=False)
    active = models.BooleanField(default=True)
    used_by = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    generated_by = models.ForeignKey(Vendor, on_delete=models.CASCADE, null=True, blank=True, editable=False)
    timestamp = models.DateTimeField(auto_now_add=True)

    def generate_coupon_code(self, length=50):
        characters = string.ascii_uppercase + string.digits
        return ''.join(random.choice(characters) for _ in range(length))

    def save(self, *args, **kwargs):
        if not self.coupon_code:
            self.coupon_code = self.generate_coupon_code()

        if self.generated_by is None:
            # If generated_by is not set, try to get the current logged-in vendor and set it as the generated_by
            user = kwargs.get('request').user if 'request' in kwargs else None
            if user:
                vendor = Vendor.objects.filter(user=user).first()
                if vendor:
                    self.generated_by = vendor

        super(CouponCode, self).save(*args, **kwargs)


    def __str__(self):
        return f"Coupon Code Generated by {self.generated_by}"