# Generated by Django 4.2.4 on 2023-08-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_paymentrequest_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='account_number',
            field=models.CharField(default='0', max_length=11),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='bank_name',
            field=models.CharField(default='a', max_length=255),
        ),
    ]
