# Generated by Django 4.2.4 on 2023-09-05 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_spin'),
    ]

    operations = [
        migrations.AddField(
            model_name='spin',
            name='last_spin',
            field=models.DateField(default=datetime.date(2023, 9, 5)),
        ),
    ]
