# Generated by Django 4.2.4 on 2023-09-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_spin_last_spin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spin',
            name='last_spin',
            field=models.DateField(),
        ),
    ]
