# Generated by Django 4.2.4 on 2023-08-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_dailyloginreward_delete_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyloginreward',
            name='daily_login_bal',
            field=models.IntegerField(default=0),
        ),
    ]
