# Generated by Django 4.2.4 on 2023-08-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_dailyloginreward_daily_login_bal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyloginreward',
            name='daily_login_bal',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
