# Generated by Django 4.2.4 on 2023-08-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_referral_referalreward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcode',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
