# Generated by Django 4.2.4 on 2023-08-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_couponcode_coupon_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_whatsapp_url',
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_whatsapp_number',
            field=models.CharField(default='6', max_length=10),
        ),
    ]
