# Generated by Django 4.2.4 on 2023-08-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_vendor_vendor_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='referalreward',
            name='referral_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
