# Generated by Django 4.2.4 on 2023-08-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_referalreward_referral_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referalreward',
            name='referral_link',
        ),
        migrations.AddField(
            model_name='useradditionalinformation',
            name='referral_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
