# Generated by Django 4.2.4 on 2023-08-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_couponcode_generated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradditionalinformation',
            name='account_bal',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
