# Generated by Django 4.2.4 on 2023-08-31 21:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_delete_dailyloginreward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradditionalinformation',
            name='image',
            field=cloudinary.models.CloudinaryField(default='hello.py', max_length=255, verbose_name='image'),
        ),
    ]
