# Generated by Django 4.2.4 on 2023-08-31 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_postshare'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postshare',
            old_name='shared_at',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='postshare',
            name='platform_shared',
            field=models.CharField(choices=[('FACEBOOK', 'FACEBOOK'), ('TWITTER', 'TWITTER'), ('LINKEDIN', 'LINKEDIN')], default='', max_length=50),
        ),
    ]
