# Generated by Django 4.2.4 on 2023-08-31 21:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_shared_at_postshare_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=cloudinary.models.CloudinaryField(default='hello.py', max_length=255, verbose_name='image'),
        ),
    ]
