# Generated by Django 4.2.4 on 2023-08-31 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postshare',
            name='platform_shared',
            field=models.CharField(choices=[('FACEBOOK', 'FACEBOOK'), ('TWITTER', 'TWITTER'), ('LINKEDIN', 'LINKEDIN'), ('WHATSAPP', 'WHATSAPP')], default='', max_length=50),
        ),
    ]
